#include <jni.h>
#include <dlfcn.h>
#include <android/log.h>
#include <stdlib.h>
#include "Substrate.h"
#include "com/mojang/minecraftpe/Common.h"
#include "com/mojang/minecraftpe/client/AppPlatform.h" 
#include "com/mojang/minecraftpe/client/AppPlatform_android.h"
//#include "com/mojang/minecraftpe/locale/I18n.h"
#include "com/mojang/minecraftpe/world/item/Item.h"
#include "com/mojang/minecraftpe/world/entity/Mob.h"
#include "com/smartdev/saomc/items/CardinalItems.h"